### ISSUE TITLE
How can I deal with 'AttributeError: 'module' object has no attribute 'stack''

### ISSUE THREAD

**Issue by sangjunnn** [lengstrom/fast-style-transfer#61]
Hi I am really newbie for linux so I need your help.

Now I am working on ubuntu 14.04 and I have already installed tensorflow, numpy, scipy, pillow and anaconda2. I was trying to test how evaluate.py works but got an message like

    /home/sj/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44:       DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
    Traceback (most recent call last):
      File "evaluate.py", line 266, in <module>
        main()
      File "evaluate.py", line 253, in main
        device=opts.device)
      File "evaluate.py", line 186, in ffwd_to_img
        ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
      File "evaluate.py", line 147, in ffwd
        preds = transform.net(img_placeholder)
      File "src/transform.py", line 14, in net
        conv_t1 = _conv_tranpose_layer(resid5, 64, 3, 2)
      File "src/transform.py", line 38, in _conv_tranpose_layer
        tf_shape = tf.stack(new_shape)
    AttributeError: 'module' object has no attribute 'stack'

Please let me know how to deal with this error.
Any help, comments or advices are appreciated.

Thanks in advance

**Comment by ashavish** [comment]
Check if your tensorflow version is what's recommended. Think it happens when you have an older version of TF.

**Comment by sangjunnn** [comment]
Oh Thank you ashavish!!
I just upgraded my tensorflow and it is working now 
Thanks a lot!!

**Comment by patthai** [comment]
I have resolved the problem by updating Tensorflow to current version.
